## Equipo: Los patrones
  - Luis Mario Escobar Rosales 420003818
  - Samantha Mora Abonce  317010945
  - Angel Castro Reyes 317251625
  - Gabriela Cruz Blanco 317032268

In [ ]:
import numpy as np
from numpy import array
from scipy import linalg as la

## Ejercicios

### Ejercicio 1



In [ ]:
# Definición de una "transformación" T

def transformacion_t(v_vector: array):
  return np.array([v_vector[0][0] + 3*v_vector[1][0], v_vector[0][0] + 2*v_vector[1][0]])

v_vector = np.array([[4],[7]])
print (transformacion_t(v_vector))

[25 18]


Tomando la definición de la transformación $T$ mostrada en la celda anterior, realice lo siguiente:
1. ¿A qué transformación corresponde la función mostrada?, por ejemplo: \
La transformación $V$ esta representada como $V:  \mathbb{R}^{2} → \mathbb{R}^{3}$ donde
$V \begin{bmatrix}
x\\
y
\end{bmatrix} = \begin{bmatrix}
x + y\\
y \\
2x
\end{bmatrix}$

Una forma de representar a $T: \mathbb{R}^2 \rightarrow  \mathbb{R}^2$ (como en el código no hay limitaciones asumimos que está en los reales), donde \

$$T \begin{bmatrix}
x\\
y
\end{bmatrix} = \begin{bmatrix}
x + 3y\\
x + 2y
\end{bmatrix}$$

2. Demuestre que $T$ es una transformación lineal

Para demostrar que esto es cierto queremos ver que abre sumas y saca escalares. Sean $U$, $V$ matrices con entradas en los reales,  y sea $\lambda$ un escalar en $\mathbb{R}$.  Empecemos por demostrar que abre sumas, es decir que $T(U+V) = T(U) + T(V)$. Tenemos lo siguiente:
$$\begin{align*}
T(u_1, u_2) &=  (u_1 + 3u_2, u_1+2u_2)\\
T(v_1, v_2) &=  (v_1 + 3v_2, v_1+2v_2)\\
\end{align*}$$

Entonces $T(U)+ T(V) = (u_1 + 3u_2+ v_1 + 3v_2,  u_1+2u_2 + v_1+2v_2)$, sabemos que nuestras entradas son reales, así que la multiplicación se distribuye respecto a la suma, así que nos queda:

$$T(U)+ T(V) = (u_1 + v_1+ 3(u_2 + v_2),  u_1+v_1+2(u_2 + v_2))$$

Por otra parte:
$$\begin{align*}
U + V &= (u_1+v_1, u_2 + v_2)\\
T(U+V) &= (u_1+v_1 + 3(u_2+v_2), u_1+v_1 + 2(u_2+v_2))\\
T(U+V) &= T(U) + T(V)
\end{align*}$$

\
Y para ver que saca escalares tenemos lo siguiente:
$$\lambda T(u_1, u_2) = \lambda (u_1 + 3u_2, u_1+2u_2) = ( \lambda (u_1 + 3u_2), \lambda (u_1+2u_2))$$  
Por otro lado, $$T(\lambda U) = T(\lambda u_1, \lambda u_2) = (\lambda u_1+ 3(\lambda u_2), \lambda u_1 + 2(\lambda u_2))$$

Tanto $\lambda$ como $u_1, u_2$ son reales, así que se cumple la asociatividad de la suma, lo que nos deja $T(\lambda U) = T(\lambda u_1 + 2\lambda u_2, \lambda u_1 + 3\lambda u_2)$, y por lo mismo también podemos usar la distributividad, así que $T(\lambda U) = T(\lambda (u_1 + 2u_2), \lambda (u_1 + 3 u_2))$,  que es precisamente $\lambda T(u_1, u_2)$.


### Ejercicio 2


Sea T una transformación, donde T está descrita de la siguiente forma: \
$T:  \mathbb{R}^{2} → \mathbb{R}^{3}$ donde
$T \begin{bmatrix}
x\\
y
\end{bmatrix} = \begin{bmatrix}
x\\
y \\
2x + 3y
\end{bmatrix}$ \
Realice lo siguiente:
1. La transformación T ¿Es lineal?
2. Defina una función en Python que represente la transformación T y evalue los vectores $v_1$ y $v_2$

In [ ]:
v1 = np.array([[1],[3]])
v2 = np.array([[10],[1]])
# Escriba su codigo aqui
def transformacion_2(v_vector: array):
  return np.array([v_vector[0][0] , v_vector[1][0], 2*v_vector[0][0] + 3*v_vector[1][0]])

print(transformacion_2(v1), transformacion_2(v2))

[ 1  3 11] [10  1 23]


### Ejercicio 3


Determina los valores propios y vectores propios de la matriz $A$.\
$A = \begin{bmatrix}
2 & 1 & 1\\
2 & 3 & 2\\
3 & 3 & 4
\end{bmatrix}$

In [ ]:
# Escriba su codigo aqui
# Definir la matriz A
A = np.array([[2, 1, 1],
           [2, 3, 2],
           [3, 3, 4]])

# Función para calcular valores y vectores propios usando scipy
def valores_vectores_propios_scipy(matriz: array):
    valores_propios, vectores_propios = la.eig(matriz)
    return valores_propios, vectores_propios

# Calcular y mostrar los valores y vectores propios de A usando scipy
valores_propios, vectores_propios = valores_vectores_propios_scipy(A)
print("Valores propios:", valores_propios)
print("Vectores propios:", vectores_propios)

Valores propios: [1.+0.j 7.+0.j 1.+0.j]
Vectores propios: [[-0.81110711  0.26726124  0.09365858]
 [ 0.32444284  0.53452248 -0.74926865]
 [ 0.48666426  0.80178373  0.65561007]]


Ahora, solamente utilizando Scipy y Numpy, obtenga el polinomio caracteristico de la matriz A

In [ ]:

import numpy as np
from numpy.polynomial import polynomial as poly

# Definir la matriz A
A = np.array([[2, 1, 1], [2, 3, 2], [3, 3, 4]])

# Calcular el polinomio característico
eigenvalues, _ = np.linalg.eig(A)
coeffs = poly.polyval(eigenvalues, [1,0,0,0])
coeffs = coeffs.tolist()
#print(coeffs)
coeffs = [int(c.real) for c in coeffs]

# Mostrar el polinomio característico
print("Polinomio característico de la matriz A:")
print(coeffs)

Polinomio característico de la matriz A:
[1, 1, 1]


### Ejercicio 4


Determine el polinomio característico de la matriz $B$ utilizando Python y haciendo las cuentas correspondientes.


$B = \begin{bmatrix}
1 & -1\\
2 & 4
\end{bmatrix}$

In [ ]:
# Escriba su codigo aqui
#Ahora determinamos el polinomio caracteristico a mano

from sympy import Matrix, symbols

# Definir la matriz B
B = np.array([[1, -1], [2, 4]])
#B = np.array([[2, 1, 1], [2, 3, 2], [3, 3, 4]])

# Tamaño de la matriz B
n = B.shape[0]

# Definir el símbolo lambda como una variable "simbólica"
lambda_ = symbols('lambda')

# Construimos la matriz A - lambda*I
A_menos_lambda_I = Matrix(B - lambda_ * np.eye(n))



# Calculamos el determinante(A - lambda*I)
det_A_menos_lambda_I = A_menos_lambda_I.det()

# Expandimos el determinante para obtener el polinomio característico
polinomio_caracteristico = det_A_menos_lambda_I.expand()

#print(polinomio_caracteristico )

# Obtenemos los coeficientes del polinomio característico
coeffs_B = [int(polinomio_caracteristico .coeff(lambda_, i)) for i in range(n, -1, -1)]

# Mostrar el polinomio característico
print("Polinomio característico de la matriz B:\n")
#print(coeffs_B)
s = ""
i = n
for c in coeffs_B :
  if c >= 0  and i != n:
    s+= " + "

  s += str(c)+"\u03BB"+ "^" + str(i) + " " if i > 0 else str(c)
  i-=1
print(s)


Polinomio característico de la matriz B:

1λ^2 -5λ^1  + 6


Determine los valores característicos de la matriz $B$ utilizando Python y haciendo las cuentas correspondientes.


In [ ]:
# Escriba su codigo aqui

# Debemos encontrar las raíces (valores característicos) del polinomio
#print(np.roots(coeffs_B))
valores_caracteristicos = [round(c) for c in np.roots(coeffs_B)]
#valores_caracteristicos = [int( c.real ) for i in np.roots(coeffs_B) ]

print("Los valores característicos son:")
for valor in valores_caracteristicos:
    print(valor)

[3. 2.]
Los valores característicos son:
3
2
