# Factorización o Descomposición LU
La factorización o descomposición LU (Lower triangular and Upper triangular) o eliminación gaussiana, es una técnica en álgebra lineal que permite expresar una matriz cuadrada como el producto de dos matrices triangulares: una matriz triangular inferior (L) y una matriz triangular superior (U).
### Descomposiciones más comunes
La descomposición LU no es única, a menos que se utilicen ciertas restricciones que son impuestas tanto a L como a U. Las mas utilizadas son:
\begin{array}{ccc}
Descomposición & Restricciones\\
Doolittle & L_{ii} = 1, i = 1,2,...,n\\
Crout & U_{ii} = 1, i = 1,2,...,n\\
Choleski & L=U^{T}
\end{array}

### Ejemplo de descomposición
Para ilustrar cómo funciona la descomposición, se utilizará la descomposición Doolittle:

In [ ]:
import numpy as np
def lu_doolittle(A):
  n = len(A)
  L = np.eye(n)
  U = np.copy(A)
  for i in range(n):
    for j in range(i + 1, n):
      L[j, i] = U[j, i] / U[i, i]
      for k in range(n):
        U[j, k] -= L[j, i] * U[i, k]
  return L, U

Para probar su funcionamiento, tenemos una matriz $A$ que queremos descomponer en las matrices $LU$ tal que $LU = A$.\
Sea $A = \begin{bmatrix}
4 & 3 & -5\\
-4 & -5 & 7\\
8 & 6 & -8
\end{bmatrix}$, tal que $A = LU$ donde $L=?$ y $U=?$  


In [ ]:
A = np.array([[4, 3, -5], [-4, -5, 7], [8, 6, -8]])
L, U = lu_doolittle(A)

Utilizando la función previamente definida, se obtiene que:\
$L = \begin{bmatrix}
1 & 0 & 0\\
-1 & 1 & 0\\
2 & 0 & 1
\end{bmatrix}$ y $U = \begin{bmatrix}
4 & 3 & -5\\
0 & -2 & 2\\
0 & 0 & 2
\end{bmatrix}$

In [ ]:
print("Matriz L:")
print(L)

print("Matriz U:")
print(U)

print("LU")
print(L@U)

Matriz L:
[[ 1.  0.  0.]
 [-1.  1.  0.]
 [ 2. -0.  1.]]
Matriz U:
[[ 4  3 -5]
 [ 0 -2  2]
 [ 0  0  2]]
LU
[[ 4.  3. -5.]
 [-4. -5.  7.]
 [ 8.  6. -8.]]


Como se puede observar, la matriz resultado de realizar la multiplicación de $LU$ es la matriz $A$.

### Resolver sistemas de ecuaciones con las matrices LU

Cuando se tiene la descomposición de A, es fácil resolver ecuaciones $Ax = b$. Primero se reescribe tal que $LUx = b$. Utilizando la notación $Ux = y$, la ecuación se convierte en $Ly = b$, la cual puede ser resuelta usando sustitución hacia delante, posteriormente, podemos utilizar sustitución hacia atrás para obtener $Ux = y$.

### Ejemplo de solución un sistema de ecuaciones


Reutilizando la matriz $A$ del ejemplo de descomposición y un vector $b$ tal que $b = \begin{bmatrix}
2\\
-4\\
6
\end{bmatrix}$

Primero resolvemos $Ly = b$:

In [ ]:
b = np.array([2,-4,6])
y = np.linalg.solve(L, b)
print("Vector y:")
print(y)

Vector y:
[ 2. -2.  2.]


Posteriormente, resolvemos $Ux = y$:

In [ ]:
x = np.linalg.solve(U, y)
print("Solución x:")
print(x)

Solución x:
[0.25 2.   1.  ]


Finalmente, obtenemos que el vector $x = \begin{bmatrix}
0.25\\
2\\
1
\end{bmatrix}$ y al realizar $Ax$ obtenemos el vector $b$.

In [ ]:
print(np.dot(A,x))

[ 2. -4.  6.]


## Referencias
J. Kiusalaas. Numerical Methods in Engineering with Python 3. Numerical Methods in
Engineering with Python 3. Cambridge University Press, 2013. isbn: 9781107033856. url:
https://books.google.com.mx/books?id=aJkXoxxoCoUC
